Repository jupyterhub/ldapauthenticator, pull requests merged in 2024-09, with the labels that each got.

#244 ci: test jupyterhub 5 and python 3.12, refresh github workflows
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: ci

#247 Update ldap testing server to the latest available version
  ci/docker-ldap.sh
Labels: maintenance

#245 Require jupyterhub 4.1.6+ and Python 3.9+
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  ldapauthenticator/__init__.py
  pyproject.toml
  setup.py
Labels: maintenance, breaking

#248 docs: add two docstrings and fix an example in another
  ldapauthenticator/ldapauthenticator.py
Labels: documentation

#249 Register authenticator class with jupyterhub as ldap
  README.md
  setup.py
Labels: enhancement

#250 refactor: put validation logic in traitlets validation functions
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#251 refactor: reduce use of temporary variables like msg for logging
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#252 Fix incorrect log message (debug level)
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#238 Escape user- or ldap-provided strings in ldap search filters
  ldapauthenticator/ldapauthenticator.py
Labels: bug

#254 tests: avoid reuse of authenticator fixture between tests and add docstring
  ldapauthenticator/tests/conftest.py
  ldapauthenticator/tests/test_ldapauthenticator.py
Labels: maintenance

#255 Transition to async functions and remove tornado dependency
  ldapauthenticator/ldapauthenticator.py
  scripts
  setup.py
Labels: maintenance

#257 Relocate example snippet from code to readme
  README.md
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#256 Require ldap3 2.9.1+ released 2021 (currently latest) as a lower bound
  setup.py
Labels: maintenance, breaking

#262 docs: fix readme example based on investigation by MakarovDi
  README.md
Labels: documentation

#168 Allow users to configure group search filter and attributes (`group_search_filter` and `group_attributes` config)
  README.md
  ldapauthenticator/ldapauthenticator.py
  ldapauthenticator/tests/test_ldapauthenticator.py
Labels: new

#264 refactor: reduce use of temporary variables
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#258 Add `tls_strategy` and deprecate `use_ssl`
  README.md
  ldapauthenticator/ldapauthenticator.py
  ldapauthenticator/tests/test_ldapauthenticator.py
Labels: new

#268 refactor: specify param names for Connection.search consistently
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#270 Fix duplicated bind operation, only one is needed
  ldapauthenticator/ldapauthenticator.py
Labels: bug

#274 Improve logging, docstring, and variable naming in `resolve_username` function
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#276 Require a unique DN to be found when using lookup_dn
  ldapauthenticator/ldapauthenticator.py
Labels: bug, breaking

#275 Add missing docs for `search_filter` and `attributes` and improve logging for `search_filter`
  README.md
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#272 Add changelog for 2.0.0b1
  CHANGELOG.md
Labels: documentation

#277 refactor: distinguish login_username from resolved_username
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#279 docs: update a few config descriptions
  README.md
  ldapauthenticator/ldapauthenticator.py
Labels: documentation

#281 tests: pass config to constructor instead of configuring after
  ldapauthenticator/tests/conftest.py
  ldapauthenticator/tests/test_ldapauthenticator.py
Labels: maintenance

#283 Validate config on startup when possible (allowed_groups, lookup_dn, bind_dn_template)
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#284 Comment consistently about escape_rdn and escape_filter_chars
  ldapauthenticator/ldapauthenticator.py
Labels: maintenance

#280 Change `use_lookup_dn_username` default value to False
  README.md
  ldapauthenticator/ldapauthenticator.py
  ldapauthenticator/tests/conftest.py
Labels: maintenance, breaking

#285 Add changelog for 2.0.0b2
  CHANGELOG.md
Labels: documentation
