Repository jupyterhub/ldapauthenticator, pull requests merged in 2024-10, with the labels that each got.

#286 Docs updates, and a few tweaks to the allow config
  ldapauthenticator/ldapauthenticator.py
Labels: enhancement, documentation

#287 Remove empty scripts file
  scripts
Labels: maintenance

#289 fix: Ensure a list `bind_dn_template` is properly validated
  ldapauthenticator/ldapauthenticator.py
Labels: bug

#291 Release 2.0.1
  CHANGELOG.md
Labels: documentation

#290 Test bind_dn_template more thoroughly
  ldapauthenticator/tests/test_ldapauthenticator.py
Labels: ci
